version: '2.3'
services:
  database:
    image: postgres:9.4
    # ports:
      # - "15432:5432"
    volumes:
      - /home/robotom/rbtm_data/rbtm_web/db:/var/lib/postgresql/data
    restart: unless-stopped
    #environment:
    #   - POSTGRES_PASSWORD=postgres

  server:
    build: .
    ports:
      - "5080:80"
    links:
      - database
    external_links:
      - rbtmstorage_server_1
    networks:
      - default
      - rbtmstorage_default
    # volumes:
    #   - ./robotom/logs:/var/www/web/robotom/logs
    restart: unless-stopped
networks:
  rbtmstorage_default:
    external: true
