version: '2.4'
services:
  database:
    container_name: rbtmweb_database_1
    image: postgres:16
    # ports:
    #   - "15432:5432"
    volumes:
      - /home/robotom/rbtm_data/rbtm_web/db:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: robotom_users
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d robotom_users"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build: .
    container_name: rbtmweb_server_1
    ports:
      - "5080:80"
    depends_on:
      database:
        condition: service_healthy
    external_links:
      - rbtmstorage_server_1
    networks:
      - default
      - rbtmstorage_default
    # volumes:
    #   - ./robotom/logs:/var/www/web/robotom/logs
    restart: unless-stopped

networks:
  rbtmstorage_default:
    external: true
